c_compiler:                 # [linux]
  - clang                   # [linux]
c_compiler_version:         # [linux]
  - 18                      # [linux]
c_stdlib_version:           # [osx or linux]
  - "11.0"                  # [osx]
  - "2.28"                  # [linux]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
